version: "3"

services:
  backend:
    container_name: uplift_backend
    build: backend
    stdin_open: true
    ports:
      - 3100:3100
    volumes:
      - ./backend:/app
      - ~/.npmrc:/root/.npmrc

  frontend:
    container_name: uplift_frontend
    build: frontend
    stdin_open: true
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app

  postgres:
    container_name: uplift_postgres
    image: postgres:14-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=""
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
